#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Dec 16, 2021 07:43:36 PM MST  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background #5e5e5e \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 708x403+329+186
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1440 847
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "mainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 1 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Create User} 
    vTcl:DefineAlias "$top.but45" "createUserBtn" vTcl:WidgetProc "mainWindow" 1
    entry $top.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -width 362 
    vTcl:DefineAlias "$top.ent47" "usernameEntry" vTcl:WidgetProc "mainWindow" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Username: 
    vTcl:DefineAlias "$top.lab50" "usernameLabel" vTcl:WidgetProc "mainWindow" 1
    entry $top.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 92 
    vTcl:DefineAlias "$top.ent51" "passwordEntry" vTcl:WidgetProc "mainWindow" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Pin (4 digits):} 
    vTcl:DefineAlias "$top.lab52" "passwordLabel" vTcl:WidgetProc "mainWindow" 1
    button $top.but53 \
        -activebackground #7fed1f -activeforeground #ff0800 \
        -background #1656d8 -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text WTF 
    vTcl:DefineAlias "$top.but53" "wtfBtn" vTcl:WidgetProc "mainWindow" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text X 
    vTcl:DefineAlias "$top.but46" "closeBtn" vTcl:WidgetProc "mainWindow" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Academy Engraved LET} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 000 
    vTcl:DefineAlias "$top.lab48" "wtfCounterLabel" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $top.lab48
    label $top.lab46 \
        -activebackground #474747 -activeforeground black -background #5e5e5e \
        -font {-family Phosphate -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {What The Fuck!} 
    vTcl:DefineAlias "$top.lab46" "wtfTitleLabel" vTcl:WidgetProc "mainWindow" 1
    menu $top.m47 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground black -background $vTcl(actual_gui_menu_bg) \
        -font menu -foreground black -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but45 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.022 -width 97 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.436 -y 0 -rely 0.209 -width 172 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.445 -y 0 -rely 0.14 -width 0 -relwidth 0.137 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.436 -y 0 -rely 0.419 -width 172 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.438 -y 0 -rely 0.342 -width 0 -relwidth 0.167 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.431 -y 0 -rely 0.626 -width 237 -relwidth 0 \
        -height 58 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.66 -y 0 -rely 0.089 -width 47 -relwidth 0 \
        -height 28 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.379 -y 0 -rely 0.304 -width 0 -relwidth 0.263 \
        -height 0 -relheight 0.091 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.395 -y 0 -rely 0.174 -width 0 -relwidth 0.266 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

